### ISSUE TITLE
UNet

### ISSUE THREAD

**Issue by gravity1989** [TiSU32/MedicalImaging#1]
Hi,

Can you upload the trained model for the UNet?

Rahul.V.

**Comment by adri-romsor** [comment]
Hi, 

We never trained the UNet model on isbi dataset, and therefore cannot provide the weights for that. You might find the pre-trained weights from the paper on the [author's website](http://lmb.informatik.uni-freiburg.de/people/ronneber/u-net/); otherwise you can use the script to train your own model.

Best,
Adriana.

**Comment by gravity1989** [comment]
I was thinking if you could help with this file: 
"/data/lisatmp4/erraqabi/results/Unet/polyp_unet_drop_1e-5_750_epoch/u_net_model.npz"

**Comment by adri-romsor** [comment]
This repository was created for an internal project and has been used to share things among us. Therefore, we do not provide any support on the code nor the models.
